### PR TITLE
Fixed #7 - Cache issues. Various improvements.

### LINKED ISSUE #7: New LruCache is created for every entry.
Instead of using a single LRUCache and drawing from it when necessary, a new LruCache is being created with every call to start(), thus the cache is never actually hit.
#8 fixes this.

### PR DESCRIPTION
**Pull request by timusus**
Fixes #7 
- The cache is now static, which means it's not recreated on every new GlidePalette.with() call.
- Don't nest IntDef inside another class.. (minor code refactoring)
- Use a WeakHashmap instead of LruCache. This allows us to keep a weak reference to the bitmap - once it's cleaned up, the Palette will be removed from the cache. See http://jakewharton.com/coercing-picasso-to-play-with-palette/
- Don't crossfade the Palette colors if we're coming from a cache hit. The assumption is that the colors have already been set, so we would be crossfading for no reason.
- Use a ColorDrawable instead of a Bitmap for the TransitionDrawable of the crossfade.

### CODE REVIEW

**Comment by karimknaebel** [comment]
Great changes!

**Comment by afollestad** [comment]
+1

**Comment by karimknaebel** [comment]
@timusus the current cache implementation doesn't work well with Glide because of the following reasons: 1. Glide reuses Bitmap objects in its internal BitmapPool, 2. Bitmap doesn't override hashCode(). The result is that the cache gets completely messed up once you've loaded a bunch of images.

**Comment by timusus** [comment]
OK, thanks for the info. I'll revert those commits and create a new PR.

**Pull request closed without merging**
